{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-postgresql-init
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS pgcrypto;

    CREATE DATABASE id;
    CREATE DATABASE register;
    CREATE DATABASE bpmn;
    CREATE DATABASE notify;
    CREATE DATABASE filestorage;
{{- end }}
