{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-rabbitmq
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/tier: infrastructure
    app.kubernetes.io/exposure: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "liquio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "liquio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
        app.kubernetes.io/tier: infrastructure
        app.kubernetes.io/exposure: internal
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.config.rabbitmq.username }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.config.rabbitmq.password }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: tmp
              mountPath: /tmp
            - name: var-log-rabbitmq
              mountPath: /var/log/rabbitmq
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: rabbitmq-data
          {{- if .Values.rabbitmq.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "liquio.fullname" . }}-rabbitmq-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
        - name: var-log-rabbitmq
          emptyDir: {}
{{- end }}
