{{- if .Values.services.task.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "liquio.namespace" . }}
  name: {{ include "liquio.fullname" . }}-task
  labels:
    {{- include "liquio.labels" . | nindent 4 }}
    app.kubernetes.io/component: task
    app.kubernetes.io/tier: backend
    app.kubernetes.io/exposure: internal
spec:
  replicas: {{ .Values.services.task.replicaCount }}
  selector:
    matchLabels:
      {{- include "liquio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: task
  template:
    metadata:
      labels:
        {{- include "liquio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: task
        app.kubernetes.io/tier: backend
        app.kubernetes.io/exposure: internal
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "liquio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "liquio.initContainer.waitForPostgres" . | nindent 8 }}
        {{- include "liquio.initContainer.waitForRabbitmq" . | nindent 8 }}
        {{- include "liquio.initContainer.waitForRedis" . | nindent 8 }}
      containers:
        - name: task
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "liquio.image" (dict "component" "task" "Values" .Values "Chart" .Chart) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.task.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "{{ .Values.services.task.targetPort }}"
          volumeMounts:
            - name: config
              mountPath: /var/www/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /test/ping
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /test/ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "liquio.fullname" . }}-task-config
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
